services:
  openssl:
    image: alpine/openssl
    command: "echo 'OpenSSL service for cert generation'"
    volumes:
      - ./nginx/certs:/certs

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: ./api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS};
    env_file:
      - .env.example
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  webapp:
    build:
      context: ./webapp/Taskolith.WebApp
      dockerfile: ../Dockerfile
    image: taskolith-webapp:latest

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - backend
    depends_on:
      - api
      - webapp
    restart: unless-stopped

volumes:
  pgdata:

networks:
  backend:
    driver: bridge